### ISSUE TITLE
Decoding MPEG-H without audio scene information (MAE) does not work

### ISSUE THREAD

**Issue by benjamin-weiss** [ittiam-systems/libmpegh#94]
There are certain MPEG-H files that cannot be decoded properly with Ittiam decoder, `libmpegh` constantly spouting `IA_MPEGH_DEC_INIT_FATAL_INVALID_MCT_ENTRIES` error.

Unfortunately we cannot share the files but here is the description of what happens (and hopefully you can reproduce it locally by disabling parsing MAE data):

- the first frame initialises everything properly
- next frame causes internal state reset in `impegh_3daudio_config_dec()` because of missing audio scene description (by invoking `memset(mpeghd_state_struct->ia_audio_specific_config, 0, sizeof(ia_audio_specific_config_struct));) ;`
- afterwards most of the data gets re-initialised but MCT part in USAC core decoder does not (it is done in `impeghd_mc_init()` which is called only in `ia_core_coder_dec_process_frame_zero()` and not for e.g. second frame);
- so when MCT data in USAC is being decoded, the decoder presumes it has zero channels and refuses to decode non-silent data returning the aforementioned error code;
- because of that decoder is fully reset and re-initialised and the cycle repeats.

We can see two possible solutions for this situation: either omit resetting USAC state in that case, zeroing only selected fields of `mpeghd_state_struct->ia_audio_specific_config` or re-initialise multichannel information as part of the reset procedure.

**Comment by SakethSathuvalli** [comment]
Hi @benjamin-weiss, We are working(internally) on some fixes in the MAE handling part. We hope this issue gets addressed with those fixes.

Thanks!

**Comment by SakethSathuvalli** [comment]
Hi @benjamin-weiss ,

Could You please let us know if this issue and issue #96 persist with the branch [multi-sig-grp-update]( https://github.com/ittiam-systems/libmpegh/tree/multi-sig-grp-update)

Thanks!

**Comment by benjamin-weiss** [comment]
Hi @sandeshvenkatesh,

Thanks for the branch with a potential fix. Unfortunately the branch does not fix any of the files where we see this specific issue. We studied the changes and it seems there is no change related to the reset of the config that wipes out current MCT information, which is what we have been describing in the ticket.

**Comment by SakethSathuvalli** [comment]
> Hi [@sandeshvenkatesh](https://github.com/sandeshvenkatesh),
> 
> Thanks for the branch with a potential fix. Unfortunately the branch does not fix any of the files where we see this specific issue. We studied the changes and it seems there is no change related to the reset of the config that wipes out current MCT information, which is what we have been describing in the ticket.

Hi @benjamin-weiss,

Thanks for the feedback! We will re-check and get back.
